name: MorkazSk
author: Morkazoid
version: 1.3
depend: []
softdepend: [MoxCore, MoxTokensDatabase, ProtocolLib, GlowAPI, MoxPerms, MoxPremiumShop, SQLibrary]
description: "Skript addon that adds special features. Created for GC2.PL Minecraft Network and skript community."
main: com.morkaz.morkazsk.MorkazSk
api-version: 1.13